name: Auto approve

on:
  pull_request_target:
    types:
      - opened
      - synchronized
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review
      
  workflow_dispatch:
    inputs: 
      pullRequestNumber:
        description: 'Pull request number to auto-approve'
        required: false

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'dependabot[bot]' || github.actor == 'adeloyedeji'
      with:
        github-token: ${{ secrets.DEPENDABOT_TOKEN }}
        pull-request: ${{ github.event.inputs.pullRequestNumber }}
